### ISSUE TITLE
ChipId architecture enum doesn't include some Sam4S variants.

### ISSUE THREAD

**Issue by john-terrell** [atsam4-rs/atsam4-hal#37]
The data sheet only document three 4S variants.   The missing variants are the SAM4SDx.

**Comment by haata** [comment]
D represents dual flash, so likely we can use the 2nd flash bank.

See: https://github.com/kiibohd/controller/blob/master/Lib/chip_version.h#L178

**Comment by haata** [comment]
Technically atsam4s16b and atsam4sa16b are different chips as well.
(difference is cache unit)

**Comment by john-terrell** [comment]
I have updated the PR for this to include family and model fields that correspond to the actual models.
